<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use SiteBundle\Entity\CartOrder;

/**
 * CartOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartOrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * ModelRepository constructor.
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(CartOrder::class));
    }

    /**
     * @param CartOrder $order
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function saveOrder(CartOrder $order)
    {
        $em = $this->getEntityManager();
        $em->persist($order);
        $em->flush();
    }

    /**
     * @param CartOrder $order
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function updateOrder(CartOrder $order)
    {
        $em = $this->getEntityManager();
        $em->merge($order);
        $em->flush();
    }

    /**
     * @param CartOrder $order
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function deleteOrder(CartOrder $order)
    {
        $em = $this->getEntityManager();
        $em->remove($order);
        $em->flush();
    }
}
