<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use SiteBundle\Entity\Message;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Message::class));
    }

    /**
     * @param Message $message
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function saveMessage(Message $message)
    {
        $em = $this->getEntityManager();
        $em->persist($message);
        $em->flush();
    }

    public function getChat($shoeId, $senderId, $recipientId)
    {
        return $this->createQueryBuilder("m")
            ->where("m.shoe = :shoeid")
            ->andWhere("m.sender = :userid OR m.sender = :userid2")
            ->andWhere("m.recipient = :userid OR m.recipient = :userid2")
            ->setParameters(["shoeid" => $shoeId, "userid" => $senderId, "userid2" => $recipientId])
            ->orderBy("m.sendTime")
            ->getQuery()
            ->getResult();
    }
}
