<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use SiteBundle\Entity\ShoeUser;

/**
 * ShoeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoeUserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * ModelRepository constructor.
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(ShoeUser::class));
    }

    /**
     * @param ShoeUser $shoeUser
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function saveShoeUser(ShoeUser $shoeUser)
    {
        $em = $this->getEntityManager();
        $em->persist($shoeUser);
        $em->flush();
    }

    public function findUserWithLowestPrice($shoeId, $sizeNum)
    {
        return $this->createQueryBuilder("q")
            ->where("q.shoe = :shoeid")
            ->andWhere("q.size = :sizenum")
            ->setParameters(["shoeid" => $shoeId, "sizenum" => $sizeNum])
            ->orderBy("q.price")
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }
}
