<?php

namespace SiteBundle\Repository;

/**
 * ShoeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoeRepository extends \Doctrine\ORM\EntityRepository
{
}
